### ISSUE TITLE
安全上报现在每天新上报需要定位不能传昨天的数据

### ISSUE THREAD

**Issue by xeonphi1** [zzzjoy-620/ctgu_yiqing_baopingan#1]
每天上报的时候都需要重新定位一遍才能上报，这样代码需要怎么改

**Comment by xeonphi1** [comment]
'szdz': re.findall(r'name="szdz"  maxlength="20" value="(.*?)" readonly>', html)[0],  # 所在地区 IndexError: list index out of range

**Comment by Kerim620** [comment]
直接写死。
'szdz': re.findall(r'name="szdz" maxlength="20" value="(.*?)" readonly>', html)[0]
改为
'szdz': '宜昌市西陵区'

**Comment by xeonphi1** [comment]
我是直接写死了，明天上报测试下

**Comment by xeonphi1** [comment]
我是直接写死了，明天看可不可以
